language: generic
sudo: required
services:
- docker
script:
- docker run -v ${TRAVIS_BUILD_DIR}:/root/src/ -w /root/src/ $DOCKER_IMAGE /bin/bash .travis-build.sh $DOCKER_IMAGE
env:
- DOCKER_IMAGE=centos:7
- DOCKER_IMAGE=centos:8
- DOCKER_IMAGE=fedora:31
- DOCKER_IMAGE=fedora:32
- DOCKER_IMAGE=fedora:33
- DOCKER_IMAGE=fedora:rawhide
matrix:
  allow_failures:
  - env: DOCKER_IMAGE=fedora:rawhide
before_deploy:
- openssl aes-256-cbc -K $encrypted_3efc8b0ffc6e_key -iv $encrypted_3efc8b0ffc6e_iv -in .copr.enc -out .copr -d
deploy:
  skip_cleanup: true
  provider: script
  script: docker run -v ${TRAVIS_BUILD_DIR}:/root/src/ -w /root/src/ fedora:latest /bin/sh -c "dnf install -y copr-cli && copr-cli --config .copr build --nowait simc/stable fedora/SPECS/fortrangis.spec"
  true:
    branch: master
    condition: $DOCKER_IMAGE = centos:8
dist: bionic
