language: generic

sudo: required

services:
    - docker

script:
    - docker run -v ${TRAVIS_BUILD_DIR}:/root/src/ -w /root/src/ $DOCKER_IMAGE /bin/bash .travis-build.sh $DOCKER_IMAGE

env:
    - DOCKER_IMAGE=centos:7
    - DOCKER_IMAGE=fedora:27
    - DOCKER_IMAGE=fedora:28
    - DOCKER_IMAGE=fedora:29
    - DOCKER_IMAGE=fedora:30
    - DOCKER_IMAGE=fedora:rawhide

matrix:
    allow_failures:
        - env: DOCKER_IMAGE=fedora:rawhide

before_deploy:
    - openssl aes-256-cbc -K $encrypted_fccef410f70d_key -iv $encrypted_fccef410f70d_iv -in .copr.enc -out .copr -d

deploy:
    skip_cleanup: true
    provider: script
    script: docker run -v ${TRAVIS_BUILD_DIR}:/root/src/ -w /root/src/ fedora:latest /bin/sh -c "dnf install -y copr-cli && copr-cli --config .copr build --nowait simc/stable fedora/SPECS/fortrangis.spec"

    on:
        branch: master
        condition: $DOCKER_IMAGE = centos:7
